# Codecov configuration for vex
# Documentation: https://docs.codecov.io/docs/codecov-yaml

# Repository configuration
codecov:
  require_ci_to_pass: true
  max_report_age: 24h
  notify:
    after_n_builds: 1
    wait_for_ci: true

# Coverage configuration
coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        threshold: 1%
        target: 70%
        base: auto
        if_ci_failed: error
        if_not_found: error
        informational: false
        only_pulls: false

      core:
        target: 80%
        threshold: 1%
        paths:
          - "!*_test.go"
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_ci_failed: error
        if_not_found: error
        informational: false
        only_pulls: true

# Files to ignore in coverage
ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/testdata/**"
  - "docs/**"
  - ".github/**"
  - "vendor/**"
  - "testing/benchmarks/**"

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true
  show_critical_paths: true
  after_n_builds: 1

# Component configuration
component_management:
  individual_components:
    - component_id: core
      name: Core
      paths:
        - "api.go"
        - "service.go"
        - "vector.go"
        - "!*_test.go"

    - component_id: chunking
      name: Chunking
      paths:
        - "chunker.go"
        - "!*_test.go"

    - component_id: providers
      name: Providers
      paths:
        - "openai/**"
        - "cohere/**"
        - "voyage/**"
        - "gemini/**"
        - "!*_test.go"

    - component_id: reliability
      name: Reliability
      paths:
        - "options.go"
        - "!*_test.go"

# Flags for different test runs
flags:
  unit:
    paths:
      - "*.go"
      - "!*_test.go"
    carryforward: true

# GitHub Checks
github_checks:
  annotations: true

# Parsers configuration
parsers:
  go:
    partials_as_hits: true

# Upload configuration
uploads:
  disable_default_path_fixes: false
